Format and readonly the colors

diff --git a/scripts/bin/minit b/scripts/bin/minit
--- a/scripts/bin/minit
+++ b/scripts/bin/minit
@@ -33,14 +33,14 @@ DEFAULT_TESTS=false
 declare -A PROJ_INFO
 
 sedi() {
-    case "$(uname -s)" in
-        Darwin*|*BSD*)
-            sed -i '' "$@"
-            ;;
-        *)
-            sed -i "$@"
-            ;;
-    esac
+  case "$(uname -s)" in
+    Darwin* | *BSD*)
+      sed -i '' "$@"
+      ;;
+    *)
+      sed -i "$@"
+      ;;
+  esac
 }
 
 print_help() {
@@ -204,17 +204,17 @@ parse_conf() {
   while [[ $# -gt 0 ]]; do
     case "$1" in
       --add)
-	local dep="$2"
-	local dep_pattern="^[[:space:]]*$(echo "$dep" | sed 's/[][\/.^$*]/\\&/g')[[:space:]]*$"
+        local dep="$2"
+        local dep_pattern="^[[:space:]]*$(echo "$dep" | sed 's/[][\/.^$*]/\\&/g')[[:space:]]*$"
 
-	if awk "/@DEPS_START@/,/@DEPS_END@/" "$file" | grep -q "$dep_pattern"; then
-	  echo "Dependency '$dep' already exists in $path"
-	else
-	  sedi "/@DEPS_START@/a\    $dep" "$file"
-	  echo "Added '$dep' to $path"
-	fi
-	shift 2
-	;;
+        if awk "/@DEPS_START@/,/@DEPS_END@/" "$file" | grep -q "$dep_pattern"; then
+          echo "Dependency '$dep' already exists in $path"
+        else
+          sedi "/@DEPS_START@/a\    $dep" "$file"
+          echo "Added '$dep' to $path"
+        fi
+        shift 2
+        ;;
 
       --remove)
         local dep="$2"
@@ -697,9 +697,9 @@ case "$MODE" in
     ;;
   conf | configure)
     if [[ $# -lt 1 ]]; then
-        echo "Error: No path specified for configure mode" >&2
-        print_help
-        exit 1
+      echo "Error: No path specified for configure mode" >&2
+      print_help
+      exit 1
     fi
     parse_conf "$@"
     ;;
